name: Android CI

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'release' ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: kkak10/pr-number-action@v1.3
        id: bh-pr-number

      - name: build-start
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: >
            Barista Handbook Build STARTED. Run: ${{ github.run_number }}.

      - name: pr-lik
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: >
            PR: https://github.com/mikhail98/barista-handbook/pull/${{ steps.bh-pr-number.outputs.pr }}

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          ./gradlew build

      - name: Send message if failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: >
            Barista Handbook Build FAILED. Run: ${{ github.run_number }}.

      - name: Generate Artifacts
        run: |
          ./gradlew bundleRelease

      - name: Upload Debug Apk
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Debug Apk
          path: app/build/outputs/apk/debug

      - name: Upload Release Apk
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Release Apk
          path: app/build/outputs/apk/release

      - name: build-finish
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: >
            Barista Handbook Build SUCCESS. Run: ${{ github.run_number }}.

      - name: artifact-lik
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: 5218142328:AAF8xJCg7DR2dQqRkGXq-exYugcJCBI4cw8
          to: -600920147
          message: >
            Artifacts: https://github.com/mikhail98/barista-handbook/actions/runs/${{ github.run_id }}

      - name: Attempt to get urls
        id: artifacts
        run: |
          echo "::set-output name=urls::$(curl -u admin:${{ secrets.GITHUB_TOKEN }} https://api.github.com/repos/mikhail98/barista-handbook/actions/artifacts |jq '.artifacts[].url')"

      - name: confirm release tag
        run: |
          echo ${{ steps.artifacts.outputs.urls }}